In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
b = np.array([[1.9, 2.6],[3.1, 4.2]])
print(b)

[[1.9 2.6]
 [3.1 4.2]]


In [10]:
#get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [11]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(2, 2)


In [12]:
# get size
print(a.size)
print(b.size)

3
4


In [ ]:
# get type
print(a.dtype)
print(b.dtype) 

int64
float64


In [15]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#get a specific element
print (c[0,5])

6


In [23]:
# get a specific row
print(c[1, :])

[ 8  9 10 11 12 13 14]


In [24]:
# get a specific col
print(c[: , 5])

[ 6 13]


In [27]:
print(c[0, 1:6:2]) # get a specific row with slicing

[2 4 6]


In [30]:
# replace
c[0,2] = 99
print(c)

c[ : , 5] = 55
print(c)

[[ 1  2 99  4  5  6  7]
 [ 8  9 55 11 12 13 14]]
[[ 1  2 99  4  5 55  7]
 [ 8  9 55 11 12 55 14]]


In [5]:
# 3d example
import numpy as np

d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
# get a specific element in 3d
print(d[1,1,2]) 

12


In [8]:
# replace
d[:,1,:] = [[20,21,22],[23,24,25]]
print(d)

[[[ 1  2  3]
  [20 21 22]]

 [[ 7 99  9]
  [23 24 25]]]
